### ISSUE TITLE
Enhance Frontend User Experience for Software Discovery Tool

### ISSUE THREAD

**Issue by ChaithanyaKrishna28** [openmainframeproject/software-discovery-tool-deploy#12]
**The current frontend interface of the Software Discovery Tool on the OpenMainframe Project's live deployed site lacks user-friendliness and could benefit from enhancements to improve usability and overall experience. This issue aims to address these shortcomings by implementing improvements to the frontend.**

Proposed Changes
1.**FAQ Section**: Introduce a separate section for FAQs with a dedicated navbar for easy access, improving user-friendliness and accessibility to frequently asked questions.
2.**Footer Alignment**: Address alignment issues in the footer section to ensure visual consistency across the site.
3.**Spacing Enhancement**: Implement proper spacing between the search bar, search button, and show description button to enhance readability and user interaction.
4. **Dark Mode/Light Mode Toggle**: Implement a toggle switch or button that allows users to switch between dark and light themes seamlessly.
5. **User Feedback Form**: Integrate a user-friendly feedback form accessible from prominent areas of the website, such as the navigation bar or footer.

**Request for Task Assignment:**
I am eager to contribute to the implementation of these proposed frontend enhancements. Could you please assign the related tasks to me within our project management system or task tracking tool? Additionally, I would appreciate access to the relevant files and resources required for frontend development to ensure seamless integration of the enhancements.

Thank you for your attention to this matter. I am committed to collaborating closely with the team to ensure the successful delivery of these improvements and look forward to contributing to the continued success of the Software Discovery Tool.

Warm regards,
Chaithanya Krishna
![Softwarediscoverytool_issues](https://github.com/openmainframeproject/software-discovery-tool-deploy/assets/122201792/3766d8c7-e3d9-4d78-b9cd-625265656f98)

**Comment by rachejazz** [comment]
Hello @ChaithanyaKrishna28 thank you for your suggestions, since this is the current mentorship plan, we're mulling over it on the main repo. This repo will be updated as the new frontend is launched in the parent repo.


Closing because of duplicity.
