### ISSUE TITLE
Add monitoring

### ISSUE THREAD

**Issue by pleia2** [openmainframeproject/software-discovery-tool-deploy#6]
We should be monitoring our production-level deployment for:

- Server outages
- Apache errors (500 is common for us!)

**Comment by pleia2** [comment]
I'll be adding this to the Icinga2 instance I'm using for my other projects.

**Comment by pleia2** [comment]
Checking for server-alive (ping and ssh) and http socket timeout (which will catch the 500 errors). Alerts go to myself and @rachejazz. Closing.

**Comment by rachejazz** [comment]
Acknowledged email received, thanks :)
